"""Unit and integration tests for ``script/check_event_snapshots.py`` (issue #1701).

The gate must guarantee that every ``#[contractevent]`` struct declared in
``contracts/stream/src/events.rs`` is covered by a committed fixture, that an
unbacked event or an orphan fixture fails, and that a payload change (rename,
retype, reorder, or topic re-placement) fails the comparison. The fixtures
themselves are regenerated by ``python3 script/check_event_snapshots.py
--update``.

The final test runs the gate against the repository as committed, so a new
event shipped without a fixture fails CI even if nobody wires the gate into a
workflow step.
"""

import importlib.util
import json
import sys
from pathlib import Path

import pytest


SCRIPT = Path(__file__).parents[1] / "script" / "check_event_snapshots.py"
SPEC = importlib.util.spec_from_file_location("check_event_snapshots", SCRIPT)
snapshots = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
sys.modules[SPEC.name] = snapshots
SPEC.loader.exec_module(snapshots)


# The canonical event inventory. A new event type must be added here, to
# ``events.rs``, and to the fixture directory in the same change.
EXPECTED_TOPICS = {
    "cancelled",
    "contract_halted",
    "contract_resumed",
    "delegate_granted",
    "delegate_revoked",
    "halt_operator_set",
    "paused",
    "recipient_transferred",
    "resumed",
    "stream_created",
    "topped_up",
    "ttl_extended",
    "withdrawn",
}


SOURCE = """\
use soroban_sdk::{contractevent, Address};

#[contractevent]
pub struct AlphaEvent {
    #[topic]
    pub stream_id: u64,
    #[topic]
    pub sender: Address,
    pub amount: i128,
    pub status: Status,
}

/// A second event in the same file.
#[contractevent]
pub struct BetaEvent {
    #[topic]
    pub operator: Address,
    /// Ledger timestamp.
    pub at: u64,
}
"""


ALPHA_FIELDS = [
    {"name": "stream_id", "type": "u64", "topic": True},
    {"name": "sender", "type": "Address", "topic": True},
    {"name": "amount", "type": "i128", "topic": False},
    {"name": "status", "type": "Status", "topic": False},
]
BETA_FIELDS = [
    {"name": "operator", "type": "Address", "topic": True},
    {"name": "at", "type": "u64", "topic": False},
]


def _schema(name: str) -> dict:
    fields = ALPHA_FIELDS if name == "AlphaEvent" else BETA_FIELDS
    return {
        "event": name,
        "topic": snapshots.snake_case(name),
        "fields": [dict(field) for field in fields],
    }


def _write_fixture(directory: Path, name: str, payload=None) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{snapshots.snake_case(name)}.json"
    path.write_text(json.dumps(payload if payload is not None else _schema(name), indent=2) + "\n")
    return path


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "name, expected",
    [
        ("StreamCreated", "stream_created"),
        ("TtlExtended", "ttl_extended"),
        ("HaltOperatorSet", "halt_operator_set"),
        ("RecipientTransferred", "recipient_transferred"),
        ("ContractResumed", "contract_resumed"),
    ],
)
def test_snake_case_matches_topic_symbols(name, expected):
    assert snapshots.snake_case(name) == expected


def test_parse_events_extracts_name_topic_and_ordered_fields():
    schemas = snapshots.parse_events(SOURCE)

    assert [schema.name for schema in schemas] == ["AlphaEvent", "BetaEvent"]

    alpha, beta = schemas
    assert alpha.topic == "alpha_event"
    assert [(field.name, field.type, field.topic) for field in alpha.fields] == [
        ("stream_id", "u64", True),
        ("sender", "Address", True),
        ("amount", "i128", False),
        ("status", "Status", False),
    ]
    # A doc comment on a field is not a field.
    assert [(field.name, field.topic) for field in beta.fields] == [
        ("operator", True),
        ("at", False),
    ]


def test_parse_events_handles_option_and_generic_types():
    source = """\
#[contractevent]
pub struct OptionEvent {
    pub expires_at: Option<u64>,
    pub reference: Option<String>,
}
"""
    (schema,) = snapshots.parse_events(source)
    assert [(field.name, field.type) for field in schema.fields] == [
        ("expires_at", "Option<u64>"),
        ("reference", "Option<String>"),
    ]


def test_parse_events_returns_empty_for_no_contractevent_structs():
    assert snapshots.parse_events("pub struct NotAnEvent { pub x: u64 }") == []


# ---------------------------------------------------------------------------
# check()
# ---------------------------------------------------------------------------


def test_check_passes_when_every_event_has_a_matching_fixture(tmp_path, capsys):
    for name in ("AlphaEvent", "BetaEvent"):
        _write_fixture(tmp_path, name)

    schemas = snapshots.parse_events(SOURCE)
    assert snapshots.check(schemas, tmp_path) == 0
    assert "2 event type(s) covered" in capsys.readouterr().out


def test_check_fails_when_a_fixture_is_missing(tmp_path, capsys):
    _write_fixture(tmp_path, "AlphaEvent")  # BetaEvent deliberately missing

    result = snapshots.check(snapshots.parse_events(SOURCE), tmp_path)

    assert result == 1
    out = capsys.readouterr().out
    assert "beta_event.json: fixture missing" in out


def test_check_fails_when_the_fixture_directory_is_absent(tmp_path, capsys):
    result = snapshots.check(snapshots.parse_events(SOURCE), tmp_path / "nope")

    assert result == 1
    assert "missing fixture directory" in capsys.readouterr().out


def test_check_fails_on_orphan_fixture_without_an_event(tmp_path, capsys):
    for name in ("AlphaEvent", "BetaEvent"):
        _write_fixture(tmp_path, name)
    (tmp_path / "ghost.json").write_text("{}\n")

    result = snapshots.check(snapshots.parse_events(SOURCE), tmp_path)

    assert result == 1
    assert "ghost.json: fixture has no matching" in capsys.readouterr().out


@pytest.mark.parametrize(
    "mutate, expected_fragment",
    [
        (lambda payload: payload["fields"][0].update({"name": "renamed"}), "payload shape changed"),
        (lambda payload: payload["fields"][0].update({"type": "u32"}), "payload shape changed"),
        (lambda payload: payload["fields"][2].update({"topic": True}), "payload shape changed"),
        (lambda payload: payload["fields"].reverse(), "payload shape changed"),
        (lambda payload: payload.update({"event": "SomethingElse"}), "event name changed"),
    ],
)
def test_check_fails_on_payload_drift(tmp_path, mutate, expected_fragment):
    payload = _schema("AlphaEvent")
    mutate(payload)
    _write_fixture(tmp_path, "AlphaEvent", payload)
    _write_fixture(tmp_path, "BetaEvent")

    result = snapshots.check(snapshots.parse_events(SOURCE), tmp_path)

    assert result == 1


def test_check_fails_on_malformed_fixture(tmp_path, capsys):
    for name in ("AlphaEvent", "BetaEvent"):
        _write_fixture(tmp_path, name)
    (tmp_path / "alpha_event.json").write_text("{not json")

    result = snapshots.check(snapshots.parse_events(SOURCE), tmp_path)

    assert result == 1
    assert "not readable JSON" in capsys.readouterr().out


# ---------------------------------------------------------------------------
# update()
# ---------------------------------------------------------------------------


def test_update_writes_a_fixture_per_event_and_prunes_stale(tmp_path, capsys):
    tmp_path.mkdir(exist_ok=True)
    (tmp_path / "gone.json").write_text("{}\n")

    assert snapshots.update(snapshots.parse_events(SOURCE), tmp_path) == 0

    assert sorted(path.name for path in tmp_path.glob("*.json")) == [
        "alpha_event.json",
        "beta_event.json",
    ]
    assert "gone.json" in capsys.readouterr().out

    # Round-trip: what update wrote must satisfy check.
    assert snapshots.check(snapshots.parse_events(SOURCE), tmp_path) == 0


# ---------------------------------------------------------------------------
# main()
# ---------------------------------------------------------------------------


def test_main_returns_2_when_events_source_is_missing(tmp_path, capsys):
    result = snapshots.main(
        ["--events", str(tmp_path / "absent.rs"), "--fixtures", str(tmp_path)]
    )

    assert result == 2
    assert "events source not found" in capsys.readouterr().err


def test_main_returns_2_when_no_event_structs_are_parsed(tmp_path, capsys):
    source = tmp_path / "events.rs"
    source.write_text("pub struct NotAnEvent { pub x: u64 }\n")

    result = snapshots.main(["--events", str(source), "--fixtures", str(tmp_path)])

    assert result == 2
    assert "no #[contractevent] structs parsed" in capsys.readouterr().err


def test_main_update_then_check_round_trips(tmp_path):
    source = tmp_path / "events.rs"
    source.write_text(SOURCE)

    assert snapshots.main(["--events", str(source), "--fixtures", str(tmp_path)]) == 1
    assert (
        snapshots.main(["--events", str(source), "--fixtures", str(tmp_path), "--update"])
        == 0
    )
    assert snapshots.main(["--events", str(source), "--fixtures", str(tmp_path)]) == 0


def test_main_fails_when_a_new_event_is_added_without_a_fixture(tmp_path, capsys):
    fixtures = tmp_path / "fixtures"
    snapshots.update(snapshots.parse_events(SOURCE), fixtures)

    new_event = (
        "\n/// Shipped without a fixture.\n"
        "#[contractevent]\n"
        "pub struct GammaEvent {\n"
        "    #[topic]\n"
        "    pub stream_id: u64,\n"
        "}\n"
    )
    source = tmp_path / "events.rs"
    source.write_text(SOURCE + new_event)

    result = snapshots.main(["--events", str(source), "--fixtures", str(fixtures)])

    assert result == 1
    assert "gamma_event.json: fixture missing" in capsys.readouterr().out


# ---------------------------------------------------------------------------
# The repository as committed — the CI-enforced guarantee
# ---------------------------------------------------------------------------


def test_committed_fixtures_cover_every_emitted_event_type():
    schemas = snapshots.parse_events(snapshots.EVENTS_RS.read_text(encoding="utf-8"))
    topics = [schema.topic for schema in schemas]

    # No two event structs may generate the same namespace symbol.
    assert len(topics) == len(set(topics))
    assert set(topics) == EXPECTED_TOPICS

    # One fixture per event, no orphans, exact payload match.
    fixture_stems = {path.stem for path in snapshots.FIXTURES_DIR.glob("*.json")}
    assert fixture_stems == EXPECTED_TOPICS
    assert snapshots.main([]) == 0


def test_committed_fixtures_pin_the_documented_topic_arity():
    schemas = {
        schema.topic: schema
        for schema in snapshots.parse_events(
            snapshots.EVENTS_RS.read_text(encoding="utf-8")
        )
    }

    # topic[0] plus every #[topic] field.
    assert len(schemas["stream_created"].topic_fields) == 3
    assert len(schemas["withdrawn"].topic_fields) == 2
    assert len(schemas["recipient_transferred"].topic_fields) == 3
    assert len(schemas["delegate_granted"].topic_fields) == 3
    assert len(schemas["ttl_extended"].topic_fields) == 1
    assert len(schemas["halt_operator_set"].topic_fields) == 1
