[package]
name = "fluxora-stream"
description = "Continuous payment streaming primitive for Soroban"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[features]
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
fluxora_factory = { path = "../factory", features = ["testutils"] }
proptest = "1"
serde_json = { workspace = true }
